### ISSUE TITLE
의미 없는 변수명 사용 자제 부탁드려요 🙏

### ISSUE THREAD

**Issue by azure-553** [hxeonxins/java-study#1]
https://github.com/hxeonxins/java-study/blob/20e7b305154d4ddba5ee7ba309aaa7b75863fa19/src/variable/Var2.java#L5

변수 이렇게 쓰시면 곤란합니다. 개발자끼리 협업 할 때 어떤 데이터가 어떤 변수에 있는지 명확하지 않기 때문이죠. 연습이라도 실제로 사용한다고 생각하면서 변수명을 지으면 좋을 것 같아요. 아래 쪽에 변수명과 관련된 글을 두고 갈게용. 꼭 읽어보시길

https://leffept.tistory.com/412

**Comment by hxeonxins** [comment]
좋은 지적 감사합니다.^^ 변수 명에 대해서는 저도 잘 숙지하고 있습니다. 강의에서도 실제로는 저렇게 쓰지 않는다고 했구요. 다른 코드들 보면 변수명이 명확하게 되어 있습니다.

**Comment by azure-553** [comment]
https://github.com/hxeonxins/java-study/blob/0c534225d6db9697e5fd111e3e72c51a70728cee/src/scope/Scope1.java#L5

그런거 치곤 여기도 ....
@hxeonxins
